/** Cron job executor that runs bounded local shell scripts. */
import { execFile } from "node:child_process";
import { relative, resolve } from "node:path";
import { promisify } from "node:util";
import type { ChannelProvider } from "@pi-crew/core";
import type { CronJobExecutionResult, CronJobExecutor, CronJobRecord, CronRunRecord } from "./types.js";
const execFileAsync = promisify(execFile); const DEFAULT_TIMEOUT_MS = 300_000; const MAX_OUTPUT_CHARS = 32_000;
export interface ScriptCronJobExecutorOptions { readonly scriptRoot: string; readonly timeoutMs?: number; readonly channelProvider?: ChannelProvider; }
export class ScriptCronJobExecutor implements CronJobExecutor { readonly #scriptRoot: string; readonly #timeoutMs: number; readonly #channelProvider: ChannelProvider | null; constructor(options: ScriptCronJobExecutorOptions) { this.#scriptRoot = resolve(options.scriptRoot); this.#timeoutMs = options.timeoutMs ?? DEFAULT_TIMEOUT_MS; this.#channelProvider = options.channelProvider ?? null; }
async execute(job: CronJobRecord, run: CronRunRecord): Promise<CronJobExecutionResult> { if (job.shape === "llm_driven") return unsupported(job, "llm_driven_requires_agent_executor"); if (job.script === null || job.script.trim().length === 0) return unsupported(job, "missing_script"); const cwd = resolveInsideRoot(this.#scriptRoot, job.cwd ?? "."); try { const result = await execFileAsync("bash", ["-lc", job.script], { cwd, timeout: this.#timeoutMs, maxBuffer: 2_000_000 }); const stdout = truncate(result.stdout); const stderr = truncate(result.stderr); await this.deliver(job, run, stdout, stderr); return { status: "succeeded", stdout, stderr, exitCode: 0, errorMessage: null }; } catch (error: unknown) { const failure = executionFailure(error); await this.deliver(job, run, failure.stdout, failure.stderr); return failure; } }
private async deliver(job: CronJobRecord, run: CronRunRecord, stdout: string, stderr: string): Promise<void> { if (this.#channelProvider === null || job.deliveryChannelId === null) return; await this.#channelProvider.sendMessage(job.deliveryChannelId, { kind: "text", text: renderDelivery(job, run, stdout, stderr), metadata: { type: "cron_run", jobId: job.id, runId: run.id } }); }}
function unsupported(job: CronJobRecord, reason: string): CronJobExecutionResult { return { status: "failed", stdout: "", stderr: "", exitCode: null, errorMessage: `cron job ${job.id} cannot run: ${reason}` }; }
function executionFailure(error: unknown): CronJobExecutionResult { if (typeof error === "object" && error !== null) { const record = error as Record<string, unknown>; return { status: "failed", stdout: truncate(typeof record["stdout"] === "string" ? record["stdout"] : ""), stderr: truncate(typeof record["stderr"] === "string" ? record["stderr"] : ""), exitCode: typeof record["code"] === "number" ? record["code"] : null, errorMessage: error instanceof Error ? error.message : "cron script failed" }; } return { status: "failed", stdout: "", stderr: "", exitCode: null, errorMessage: String(error) }; }
function renderDelivery(job: CronJobRecord, run: CronRunRecord, stdout: string, stderr: string): string { const sections = [`cron job ${job.id} run ${run.id} completed`]; if (stdout.trim().length > 0) sections.push(`stdout:\n${stdout}`); if (stderr.trim().length > 0) sections.push(`stderr:\n${stderr}`); return sections.join("\n\n"); }
function resolveInsideRoot(rootPath: string, requested: string): string { const path = resolve(rootPath, requested); const rel = relative(rootPath, path); if (rel.startsWith("..") || rel.startsWith("/")) throw new CronExecutionError(`cron cwd escapes script root: ${requested}`); return path; }
function truncate(value: string): string { return value.length <= MAX_OUTPUT_CHARS ? value : `${value.slice(0, MAX_OUTPUT_CHARS)}\n[truncated]`; }
export class CronExecutionError extends Error { readonly code = "CRON_EXECUTION_ERROR"; constructor(message: string) { super(message); this.name = "CronExecutionError"; } }
