/** SQLite-backed cron job repository. */
import type Database from "better-sqlite3";
import { CronExpression } from "./cron-expression.js";
import type { CronJobDraft, CronJobRecord, CronJobRepository, CronJobShape, CronRunCompletion, CronRunRecord, CronRunStatus } from "./types.js";
interface CronJobRow { readonly id: string; readonly project_id: string; readonly schedule: string; readonly shape: string; readonly prompt: string | null; readonly script: string | null; readonly cwd: string | null; readonly delivery_channel_id: string | null; readonly enabled: number; readonly timezone: string; readonly next_run_at: string | null; readonly last_run_at: string | null; readonly created_at: string; readonly updated_at: string; }
interface CronRunRow { readonly id: string; readonly job_id: string; readonly started_at: string; readonly finished_at: string | null; readonly status: string; readonly stdout: string; readonly stderr: string; readonly exit_code: number | null; readonly error_message: string | null; }
export class SqliteCronJobRepository implements CronJobRepository { constructor(private readonly db: Database.Database) {}
async upsert(job: CronJobDraft, now: Date): Promise<CronJobRecord> { const timestamp = now.toISOString(); const nextRunAt = job.enabled === false ? null : new CronExpression(job.schedule).nextAfter(now).toISOString(); this.db.prepare(`INSERT INTO cron_jobs (id, project_id, schedule, shape, prompt, script, cwd, delivery_channel_id, enabled, timezone, next_run_at, last_run_at, created_at, updated_at) VALUES (@id, @project_id, @schedule, @shape, @prompt, @script, @cwd, @delivery_channel_id, @enabled, @timezone, @next_run_at, NULL, @created_at, @updated_at) ON CONFLICT(id) DO UPDATE SET project_id=excluded.project_id, schedule=excluded.schedule, shape=excluded.shape, prompt=excluded.prompt, script=excluded.script, cwd=excluded.cwd, delivery_channel_id=excluded.delivery_channel_id, enabled=excluded.enabled, timezone=excluded.timezone, next_run_at=excluded.next_run_at, updated_at=excluded.updated_at`).run({ id: job.id, project_id: job.projectId, schedule: job.schedule, shape: job.shape, prompt: job.prompt ?? null, script: job.script ?? null, cwd: job.cwd ?? null, delivery_channel_id: job.deliveryChannelId ?? null, enabled: job.enabled === false ? 0 : 1, timezone: job.timezone ?? "UTC", next_run_at: nextRunAt, created_at: timestamp, updated_at: timestamp }); return this.require(job.id); }
get(jobId: string): Promise<CronJobRecord | null> { const row = this.db.prepare("SELECT * FROM cron_jobs WHERE id = ?").get(jobId) as CronJobRow | undefined; return Promise.resolve(row === undefined ? null : jobFromRow(row)); }
list(projectId?: string): Promise<readonly CronJobRecord[]> { const rows = projectId === undefined ? this.db.prepare("SELECT * FROM cron_jobs ORDER BY id").all() as CronJobRow[] : this.db.prepare("SELECT * FROM cron_jobs WHERE project_id = ? ORDER BY id").all(projectId) as CronJobRow[]; return Promise.resolve(rows.map(jobFromRow)); }
due(now: Date): Promise<readonly CronJobRecord[]> { const rows = this.db.prepare("SELECT * FROM cron_jobs WHERE enabled = 1 AND next_run_at IS NOT NULL AND next_run_at <= ? ORDER BY next_run_at, id").all(now.toISOString()) as CronJobRow[]; return Promise.resolve(rows.map(jobFromRow)); }
delete(jobId: string): Promise<boolean> { return Promise.resolve(this.db.prepare("DELETE FROM cron_jobs WHERE id = ?").run(jobId).changes > 0); }
startRun(job: CronJobRecord, runId: string, startedAt: Date): Promise<CronRunRecord> { this.db.prepare("INSERT INTO cron_runs (id, job_id, started_at, status) VALUES (?, ?, ?, 'running')").run(runId, job.id, startedAt.toISOString()); return Promise.resolve(this.requireRun(runId)); }
completeRun(runId: string, completion: CronRunCompletion): Promise<CronRunRecord> { this.db.prepare("UPDATE cron_runs SET finished_at=?, status=?, stdout=?, stderr=?, exit_code=?, error_message=? WHERE id=?").run(completion.finishedAt, completion.status, completion.stdout, completion.stderr, completion.exitCode, completion.errorMessage, runId); return this.requireRun(runId); }
reschedule(jobId: string, lastRunAt: Date, nextRunAt: Date | null): Promise<void> { this.db.prepare("UPDATE cron_jobs SET last_run_at=?, next_run_at=?, updated_at=? WHERE id=?").run(lastRunAt.toISOString(), nextRunAt?.toISOString() ?? null, new Date().toISOString(), jobId); }
recentRuns(jobId: string, limit: number): Promise<readonly CronRunRecord[]> { const rows = this.db.prepare("SELECT * FROM cron_runs WHERE job_id = ? ORDER BY started_at DESC LIMIT ?").all(jobId, Math.max(1, Math.min(limit, 100))) as CronRunRow[]; return Promise.resolve(rows.map(runFromRow)); }
private async require(jobId: string): Promise<CronJobRecord> { const job = await this.get(jobId); if (job === null) throw new CronRepositoryError(`cron job not found after write: ${jobId}`); return job; }
private requireRun(runId: string): CronRunRecord { const row = this.db.prepare("SELECT * FROM cron_runs WHERE id = ?").get(runId) as CronRunRow | undefined; if (row === undefined) throw new CronRepositoryError(`cron run not found after write: ${runId}`); return runFromRow(row); }}
export class CronRepositoryError extends Error { readonly code = "CRON_REPOSITORY_ERROR"; constructor(message: string) { super(message); this.name = "CronRepositoryError"; } }
function jobFromRow(row: CronJobRow): CronJobRecord { return { id: row.id, projectId: row.project_id, schedule: row.schedule, shape: row.shape as CronJobShape, prompt: row.prompt, script: row.script, cwd: row.cwd, deliveryChannelId: row.delivery_channel_id, enabled: row.enabled === 1, timezone: row.timezone, nextRunAt: row.next_run_at, lastRunAt: row.last_run_at, createdAt: row.created_at, updatedAt: row.updated_at }; }
function runFromRow(row: CronRunRow): CronRunRecord { return { id: row.id, jobId: row.job_id, startedAt: row.started_at, finishedAt: row.finished_at, status: row.status as CronRunStatus, stdout: row.stdout, stderr: row.stderr, exitCode: row.exit_code, errorMessage: row.error_message }; }
